services:

    nginx-ssl:
        build: ./docker/nginx
        container_name: nginx-ssl
        restart: always
        environment:
            - TZ=Europe/Moscow
        volumes:
            - ./src:/src
            - ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/logs:/var/log/nginx
        ports:
            - 80:80
            - 443:443
        links:
            - php

    php:
        build: ./docker/php
        container_name: php
        restart: always
        volumes:
            - ./src:/src
            - ./docker/etc/php/php.ini:/usr/local/etc/php/php.ini
#            - ./docker/etc/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        ports:
            - 9000:9000
        links:
            - mysql

    mysql:
        image: mysql:8
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_DATABASE=gigant
            - MYSQL_USER=local
            - MYSQL_PASSWORD=local
            - MYSQL_ROOT_PASSWORD=local
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/etc/mysql:/etc/mysql/conf.d
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        ports:
            - 8080:80
